# blog 静态资源相关配置 (需要和docker的挂载目录一致)
blog:
  static-locations: /server/static
  content-image-prefix: /api/image/content
  cover-image-prefix: /api/image/cover

# spring 相关配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/programmingroad?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: eL4Np8-qW%)1
  redis:
    host: localhost
    port: 6379
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  resources:
    static-locations: file:${blog.static-locations}

# mp相关配置
mybatis-plus:
  type-enums-package: com.programmingroad.blog.enums

# http相关配置
httpclient:
  conTimeout: 3000   #连接超时时间
  soTimeout: 30000   #响应超时时间

# github相关配置
github:
  clientId: 90311b932a081ea68e12
  clientSecret: 3bfa18de6d5e89050a898d8e696c176ce96b8973
  accessTokenUrl: https://github.com/login/oauth/access_token
  userUrl: https://api.github.com/user
  login: programmingroad